/* SWIR XBookmark Launcher 4.0 — STABLE ONLY */
(()=>{try{
if(window.__SWIR_LAUNCHER_OPEN){document.getElementById('swirLauncher100')?.remove();window.__SWIR_LAUNCHER_OPEN=0}
window.__SWIR_LAUNCHER_OPEN=1;
const CDN='https://cdn.jsdelivr.net/gh/Swir/XBookmark@';
const versions=[
{id:'10.17.1',label:'10.17.1',tag:'RECOMMENDED',icon:'S',ref:'ca44d190ed8dfbad4b2e7dc90963f19e9d780dd4',file:'swir-stable-10171.js',desc:'APK EXACT Friend Radar + pełny MIX 8/8 + przebudowany kolorowy ICE. Pokazuje globalne rooms[] bez APP/PC/telefonów.',accent:'#55e69a'},
{id:'9.9.2',label:'9.9.2',tag:'ROLLBACK',icon:'S',ref:'c16d6ec57b9063cd9c731f501e5c0cc14adb5c60',file:'swir-stable-992.js',desc:'Poprzednia sprawdzona wersja stabilna.',accent:'#62cfff'},
{id:'9.9.1',label:'9.9.1',tag:'ROLLBACK',icon:'S',ref:'bd40a1f33f565092025a619bfe7742ee55569fba',file:'swir-stable-991.js',desc:'Starszy rollback Stable.',accent:'#56e6a5'},
{id:'9.9',label:'9.9',tag:'ARCHIVE',icon:'S',ref:'8ef1a5773f98780094c65042c2e622852ea6eb29',file:'swir.js',desc:'Zamrożona baza 9.9.',accent:'#00e5ff'},
{id:'9.8',label:'9.8',tag:'ARCHIVE',icon:'S',ref:'bf0ae7562016d82699baf834664b0945320102ba',file:'swir.js',desc:'Starsza stabilna wersja Friend UX + motywy.',accent:'#56e6a5'},
{id:'9.7',label:'9.7',tag:'ARCHIVE',icon:'S',ref:'868963711b94d373eee7d6cc1a7444da3c89ef45',file:'swir.js',desc:'Starszy Friend Radar.',accent:'#72b7ff'},
{id:'9.6',label:'9.6',tag:'SAFE ARCHIVE',icon:'S',ref:'9c4528f269d931f483989dd4dff591bb2a93fa31',file:'swir.js',desc:'Najstarsza baza ratunkowa.',accent:'#a8b5c2'}
];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!document.getElementById('swirLauncherCss')){const s=document.createElement('style');s.id='swirLauncherCss';s.textContent=`#swirLauncher100{position:fixed;inset:0;z-index:2147483646;background:rgba(3,7,13,.84);backdrop-filter:blur(10px);display:flex;align-items:center;justify-content:center;font-family:Inter,Segoe UI,Arial,sans-serif;color:#eef8ff}#swirLauncher100 *{box-sizing:border-box}#swirLauncherCard{width:min(780px,95vw);max-height:90vh;overflow:hidden;background:#08131f;border:1px solid #00dfff77;border-radius:18px;box-shadow:0 25px 80px #000c}.sxl-head{display:flex;align-items:center;gap:12px;padding:16px 18px;border-bottom:1px solid #ffffff12}.sxl-logo{font-size:22px;font-weight:1000;color:#55eaff}.sxl-title{font-weight:900;font-size:16px}.sxl-sub{font-size:10px;color:#8198aa;margin-top:2px}.sxl-stable{display:inline-block;margin-top:5px;font-size:8px;padding:3px 7px;border-radius:99px;border:1px solid #55e69a;color:#8effc4}.sxl-x{margin-left:auto;width:34px;height:34px;border-radius:9px;border:1px solid #ffffff18;background:#101d2a;color:#fff;cursor:pointer}.sxl-body{padding:13px 14px 15px;max-height:72vh;overflow:auto}.sxl-status{margin:0 0 9px;color:#8fa8bc;font-size:10px}.sxl-grid{display:grid;gap:8px}.sxl-row{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:11px 12px;border:1px solid #ffffff13;background:#0d1926;border-radius:12px}.sxl-row:first-child{background:linear-gradient(135deg,#0d2024,#102936);border-color:#55e69a66}.sxl-name{font-size:14px;font-weight:900}.sxl-icon{display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:5px;border:1px solid var(--a);color:var(--a);font-size:9px;margin-right:5px}.sxl-tag{display:inline-block;margin-left:7px;font-size:8px;padding:2px 5px;border-radius:99px;border:1px solid var(--a);color:var(--a)}.sxl-desc{font-size:10px;color:#8da4b7;margin-top:4px;line-height:1.35}.sxl-run{min-width:112px;padding:8px 10px;border-radius:9px;border:1px solid var(--a);background:#101d2c;color:#fff;font-weight:900;cursor:pointer}.sxl-foot{display:flex;gap:8px;align-items:center;margin-top:12px;padding-top:11px;border-top:1px solid #ffffff10;font-size:9px;color:#6f869a}.sxl-last{margin-left:auto;background:none;border:0;color:#88ddff;cursor:pointer;font-size:9px}@media(max-width:580px){.sxl-row{grid-template-columns:1fr}.sxl-run{width:100%}}`;document.head.appendChild(s)}
function close(){document.getElementById('swirLauncher100')?.remove();window.__SWIR_LAUNCHER_OPEN=0}
function loadVersion(v){if(!v)return;if(window._swirModIsRunning){alert('SWIR jest już uruchomiony. Zrób F5 i wybierz wersję ponownie.');return}localStorage.setItem('swir_launcher_last',v.id);const st=document.querySelector('#swirLauncher100 .sxl-status');if(st)st.textContent='Ładuję SWIR '+v.label+'…';const s=document.createElement('script');s.src=CDN+v.ref+'/'+v.file+'?v='+Date.now();s.onload=()=>{if(st)st.textContent='SWIR '+v.label+' załadowany';setTimeout(close,350)};s.onerror=()=>{if(st)st.textContent='Błąd ładowania '+v.label};document.head.appendChild(s)}
const stored=localStorage.getItem('swir_launcher_last'),lastV=versions.find(v=>v.id===stored)||versions[0];const d=document.createElement('div');d.id='swirLauncher100';d.innerHTML=`<div id="swirLauncherCard"><div class="sxl-head"><div class="sxl-logo">SWIR</div><div><div class="sxl-title">XBOOKMARK LAUNCHER <span style="font-size:9px;color:#72889b">v4.0</span></div><div class="sxl-sub">STABLE ONLY • Friend Radar APK EXACT • MIX 8/8 • ICE Color Rework</div><span class="sxl-stable">BEZ KANAŁU BETA</span></div><button class="sxl-x">×</button></div><div class="sxl-body"><div class="sxl-status">Gotowy • recommended: 10.17.1 STABLE</div><div class="sxl-grid">${versions.map(v=>`<div class="sxl-row" style="--a:${v.accent}"><div><div class="sxl-name"><span class="sxl-icon">${esc(v.icon)}</span>SWIR ${esc(v.label)}<span class="sxl-tag">${esc(v.tag)}</span></div><div class="sxl-desc">${esc(v.desc)}</div></div><button class="sxl-run" data-v="${v.id}">URUCHOM</button></div>`).join('')}</div><div class="sxl-foot"><span>10.17.1 = działający globalny Radar + 8 stylów MIX + czytelny ICE.</span><button class="sxl-last">Uruchom ostatnią →</button></div></div></div>`;d.addEventListener('click',e=>{if(e.target===d)close()});d.querySelector('.sxl-x').onclick=close;d.querySelectorAll('.sxl-run').forEach(b=>b.onclick=()=>loadVersion(versions.find(v=>v.id===b.dataset.v)));d.querySelector('.sxl-last').onclick=()=>loadVersion(lastV);document.body.appendChild(d);window.SWIR_LAUNCHER={version:'4.0',versions,close,load:id=>loadVersion(versions.find(v=>v.id===id))};
}catch(e){console.error('SWIR Launcher',e);alert('SWIR Launcher: '+e.message)}})();