/* SWIR XBookmark Launcher 5.4 — STABLE + BETA */
(()=>{try{
if(window.__SWIR_LAUNCHER_OPEN){document.getElementById('swirLauncher100')?.remove();window.__SWIR_LAUNCHER_OPEN=0}
window.__SWIR_LAUNCHER_OPEN=1;
const CDN='https://cdn.jsdelivr.net/gh/Swir/XBookmark@';
const versions=[
{id:'10.29',channel:'stable',label:'10.29 STABLE',tag:'RECOMMENDED',ref:'d59d32f5c4de212fc6b7022c238ced7e4c719a9c',file:'swir-stable-1029.js',desc:'Naprawia nicki z dwukropkiem i innymi znakami, zachowuje pełną tożsamość w Friends/rooms[], zabezpiecza routing ACK → 85 przy wielu socketach i scala świeże snapshoty 159.',accent:'#55e69a'},
{id:'10.17.2',channel:'stable',label:'10.17.2 STABLE',tag:'PREVIOUS',ref:'82c16fa72b16ce8a83fc496ed3b33f5df665a53a',file:'swir-stable-10172.js',desc:'APK Exact Friends, MIX 8/8 i ICE v2. Zachowuje natywną strukturę nicków oraz stabilny panel lokalizacji znajomych.',accent:'#62cfff'},
{id:'10.17.1',channel:'stable',label:'10.17.1 STABLE',tag:'PREVIOUS',ref:'ca44d190ed8dfbad4b2e7dc90963f19e9d780dd4',file:'swir-stable-10171.js',desc:'APK Exact Rooms, MIX 8/8 i przebudowane kolory ICE.',accent:'#72b7ff'},
{id:'10.28-beta',channel:'beta',label:'10.28 BETA',tag:'ACK ROUTE GUARD',ref:'805ef6445c59ad1e0bee6c0a86e0d0d90aac6ded',file:'swir-beta-1028.js',desc:'Naprawia routing code 85 przy wielu połączeniach: używa świeżych ACK per socket i nie zgaduje przy kilku równoczesnych kandydatach.',accent:'#5cf0c8'},
{id:'10.27-beta',channel:'beta',label:'10.27 BETA',tag:'ACK ROUTE PIN',ref:'f92d5a06a4281f3835e55319d7fcd0a54ce2751a',file:'swir-beta-1027.js',desc:'Przypina code 85 do socketu z ostatnim świeżym ACK 8/4, ograniczając rozjazd między potwierdzeniem znajomego a pobieraniem 159.',accent:'#4ff0d0'},
{id:'10.26-beta',channel:'beta',label:'10.26 BETA',tag:'ACK ROUTE TRACE',ref:'591336feb3d7a21ce9ce9711c795b724b60446d1',file:'swir-beta-1026.js',desc:'Dodaje śledzenie trasy ACK 8/4 → code 85 per połączenie, aby wykrywać błędny socket bez zmiany routingu.',accent:'#66e6ff'}
];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
if(!document.getElementById('swirLauncherCss')){const s=document.createElement('style');s.id='swirLauncherCss';s.textContent=`#swirLauncher100{position:fixed;inset:0;z-index:2147483646;background:rgba(3,7,13,.84);backdrop-filter:blur(10px);display:flex;align-items:center;justify-content:center;font-family:Inter,Segoe UI,Arial,sans-serif;color:#eef8ff}#swirLauncher100 *{box-sizing:border-box}#swirLauncherCard{width:min(760px,95vw);max-height:90vh;overflow:hidden;background:#08131f;border:1px solid #00dfff77;border-radius:18px;box-shadow:0 25px 80px #000c}.sxl-head{display:flex;align-items:center;gap:12px;padding:16px 18px;border-bottom:1px solid #ffffff12}.sxl-logo{font-size:20px;font-weight:1000;color:#55eaff}.sxl-title{font-weight:900;font-size:16px}.sxl-sub{font-size:10px;color:#8198aa;margin-top:2px}.sxl-x{margin-left:auto;width:34px;height:34px;border-radius:9px;border:1px solid #ffffff18;background:#101d2a;color:#fff;cursor:pointer}.sxl-tabs{display:flex;gap:7px;padding:10px 14px 8px;border-bottom:1px solid #ffffff0d}.sxl-tab{flex:1;padding:9px;border-radius:9px;border:1px solid #ffffff14;background:#0d1926;color:#a9bdcc;font-weight:900;cursor:pointer}.sxl-tab.active{color:#fff;border-color:#00dfff77;background:#102639}.sxl-body{padding:12px 14px 15px;max-height:68vh;overflow:auto}.sxl-status{margin:0 0 9px;color:#8fa8bc;font-size:10px}.sxl-grid{display:grid;gap:8px}.sxl-row{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:11px 12px;border:1px solid #ffffff13;background:#0d1926;border-radius:12px}.sxl-name{font-size:14px;font-weight:900}.sxl-tag{display:inline-block;margin-left:7px;font-size:8px;padding:2px 5px;border-radius:99px;border:1px solid var(--a);color:var(--a)}.sxl-desc{font-size:10px;color:#8da4b7;margin-top:4px;line-height:1.35}.sxl-run{min-width:112px;padding:8px 10px;border-radius:9px;border:1px solid var(--a);background:#101d2c;color:#fff;font-weight:900;cursor:pointer}.sxl-foot{margin-top:12px;padding-top:11px;border-top:1px solid #ffffff10;font-size:9px;color:#6f869a}@media(max-width:580px){.sxl-row{grid-template-columns:1fr}.sxl-run{width:100%}}`;document.head.appendChild(s)}
function close(){document.getElementById('swirLauncher100')?.remove();window.__SWIR_LAUNCHER_OPEN=0}
function loadVersion(v){if(!v)return;if(window._swirModIsRunning){alert('SWIR jest już uruchomiony. Zrób F5 i wybierz wersję ponownie.');return}localStorage.setItem('swir_launcher_last',v.id);const st=document.querySelector('#swirLauncher100 .sxl-status');if(st)st.textContent='Ładuję '+v.label+'…';const s=document.createElement('script');s.src=CDN+v.ref+'/'+v.file+'?v='+Date.now();s.onload=()=>{if(st)st.textContent=v.label+' załadowany';setTimeout(close,350)};s.onerror=()=>{if(st)st.textContent='Błąd ładowania '+v.label};document.head.appendChild(s)}
const stored=localStorage.getItem('swir_launcher_last'),last=versions.find(v=>v.id===stored)||versions[0],start=last.channel||'stable';const d=document.createElement('div');d.id='swirLauncher100';d.innerHTML=`<div id="swirLauncherCard"><div class="sxl-head"><div class="sxl-logo">SWIR MOD</div><div><div class="sxl-title">XBOOKMARK <span style="font-size:9px;color:#72889b">v5.4</span></div><div class="sxl-sub">3 wersje Stable • 3 wersje Beta</div></div><button class="sxl-x">×</button></div><div class="sxl-tabs"><button class="sxl-tab" data-tab="stable">STABLE</button><button class="sxl-tab" data-tab="beta">BETA</button></div><div class="sxl-body"><div class="sxl-status">Gotowy • rekomendowana wersja: 10.29 STABLE</div><div class="sxl-grid"></div><div class="sxl-foot">10.29 STABLE: symbol-safe nick identity • ACK Route Guard • snapshot merge • clean Friends panel • MIX 8/8 • ICE dark text</div></div></div>`;
function show(tab){d.querySelectorAll('.sxl-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const g=d.querySelector('.sxl-grid');g.innerHTML=versions.filter(v=>v.channel===tab).map(v=>`<div class="sxl-row" style="--a:${v.accent}"><div><div class="sxl-name">${esc(v.label)}<span class="sxl-tag">${esc(v.tag)}</span></div><div class="sxl-desc">${esc(v.desc)}</div></div><button class="sxl-run" data-v="${v.id}">URUCHOM</button></div>`).join('');g.querySelectorAll('.sxl-run').forEach(b=>b.onclick=()=>loadVersion(versions.find(v=>v.id===b.dataset.v)))}
d.addEventListener('click',e=>{if(e.target===d)close()});d.querySelector('.sxl-x').onclick=close;d.querySelectorAll('.sxl-tab').forEach(b=>b.onclick=()=>show(b.dataset.tab));document.body.appendChild(d);show(start);window.SWIR_LAUNCHER={version:'5.4',versions,close,load:id=>loadVersion(versions.find(v=>v.id===id)),show};
}catch(e){console.error('SWIR Launcher',e);alert('SWIR Launcher: '+e.message)}})();
