/* SWIR 9.9 UI/UX FINAL POLISH — clean header + 6 themes + slim friends panel */
(()=>{try{
if(window.__SWIR_UI99)return;window.__SWIR_UI99=1;
window.SWIR_UI_VERSION='9.9 FINAL POLISH';
const FRIEND_KEY='czateria_znajomi',THEME_KEY='swir_theme_99';
const pal=['#59e8ff','#75f0bd','#ffd36a','#ff8fd3','#a9a2ff','#ff9c68','#8ee66b','#6fb7ff','#f78686','#d0a0ff','#67f0e1','#f6b0ff'];
const key=n=>String(n||'').trim().toLocaleLowerCase('pl-PL');
function hash(s){let h=2166136261;for(const c of key(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h)}
function nickColor(n){return pal[hash(n)%pal.length]}
function conns(){let z=new Set();try{let m=CHNS.connManager,c=m.getCurrentConnection?.();c&&z.add(c);c=m.getFirstConnection?.();c&&z.add(c);Object.values(CHNS.channelManager?.channels||{}).forEach(ch=>{try{let x=m.getConnectionRelatedWithId?.(ch?.getChannelId?.());x&&z.add(x)}catch(e){}})}catch(e){}return[...z]}
function isMobile(n){for(const c of conns())try{let u=c.getUserWithName?.(n);if(u)return !!(u.isMobile?.()||u.isMobileUser)}catch(e){}return false}
function nickText(el){return String(el?.childNodes?.[0]?.textContent||el?.textContent||'').replace(/\s*:\s*$/,'').trim()}
function decorateNick(el){try{if(!el||el.dataset.swir99nick==='1')return;let n=nickText(el);if(!n)return;el.dataset.swir99nick='1';el.style.setProperty('color',nickColor(n),'important');el.style.setProperty('font-weight','800','important');el.style.setProperty('text-shadow','0 0 4px currentColor','important');el.style.setProperty('animation','none','important');el.style.setProperty('transition','none','important');if(isMobile(n)&&!el.querySelector('.swir-mobile-99')){let b=document.createElement('span');b.className='swir-mobile-99';b.textContent=' 📱';b.title='Użytkownik mobilny';b.style.cssText='font-size:9px;opacity:.56;text-shadow:none!important;filter:none!important';el.appendChild(b)}}catch(e){}}
function sweepNicks(root=document){root.querySelectorAll?.('[id^="m-messages_"] .m-msg-item-user-login').forEach(decorateNick)}
const themes={
 gaming:{name:'🎮 Gaming Neon',accent:'#00e5ff',accent2:'#7657ff',rgb:'0,229,255',body:'#05080d',chat1:'#0a1019',chat2:'#080d15',panel:'#0d1723',panel2:'#101b28',input:'#0b1521',text:'#e7eef7',muted:'#8298ad'},
 steel:{name:'🩶 Steel Gray',accent:'#a8d8ff',accent2:'#7896b2',rgb:'168,216,255',body:'#20242a',chat1:'#3a414a',chat2:'#2f353d',panel:'#333a43',panel2:'#3c444e',input:'#2f363e',text:'#f3f6f8',muted:'#c0c8cf'},
 ice:{name:'❄️ Ice Light',accent:'#159ee8',accent2:'#68c7ff',rgb:'21,158,232',body:'#bfe4fb',chat1:'#ffffff',chat2:'#f7fbff',panel:'#dcefff',panel2:'#cce7fa',input:'#ffffff',text:'#17324a',muted:'#5f7f98'},
 matrix:{name:'🟢 Matrix',accent:'#43ff8b',accent2:'#18b85d',rgb:'67,255,139',body:'#030906',chat1:'#07130d',chat2:'#040d08',panel:'#08160f',panel2:'#0b1c13',input:'#07150e',text:'#dfffea',muted:'#88b99a'},
 ocean:{name:'🌊 Ocean',accent:'#45d9ff',accent2:'#2580ff',rgb:'69,217,255',body:'#041018',chat1:'#081d29',chat2:'#061720',panel:'#0a2230',panel2:'#0d2b3c',input:'#092331',text:'#e6f8ff',muted:'#8bb8c8'},
 violet:{name:'💜 Violet',accent:'#d28cff',accent2:'#755cff',rgb:'210,140,255',body:'#0b0711',chat1:'#191126',chat2:'#120c1c',panel:'#1a1226',panel2:'#241732',input:'#191125',text:'#f5ebff',muted:'#b9a2c9'}
};
function themeName(){let n=localStorage.getItem(THEME_KEY)||localStorage.getItem('swir_theme_98')||'gaming';return themes[n]?n:'gaming'}
function applyTheme(n,save=1){if(!themes[n])n='gaming';let t=themes[n],r=document.documentElement;r.dataset.swirTheme99=n;r.dataset.swirTheme98=n;r.style.setProperty('--sw99-accent',t.accent);r.style.setProperty('--sw99-accent2',t.accent2);r.style.setProperty('--sw99-rgb',t.rgb);r.style.setProperty('--sw99-body',t.body);r.style.setProperty('--sw99-chat1',t.chat1);r.style.setProperty('--sw99-chat2',t.chat2);r.style.setProperty('--sw99-panel',t.panel);r.style.setProperty('--sw99-panel2',t.panel2);r.style.setProperty('--sw99-input',t.input);r.style.setProperty('--sw99-text',t.text);r.style.setProperty('--sw99-muted',t.muted);r.style.setProperty('--swir-a',t.accent);r.style.setProperty('--swir-b',t.accent2);r.style.setProperty('--swir-rgb',t.rgb);if(save){localStorage.setItem(THEME_KEY,n);localStorage.setItem('swir_theme_98',n)}document.querySelectorAll('[data-swir-theme99-btn]').forEach(b=>b.classList.toggle('active',b.dataset.swirTheme99Btn===n))}
function installCss(){if(document.getElementById('swir-ui99css'))return;let s=document.createElement('style');s.id='swir-ui99css';s.textContent=`
:root{--sw99-accent:#00e5ff;--sw99-accent2:#7657ff;--sw99-rgb:0,229,255;--sw99-body:#05080d;--sw99-chat1:#0a1019;--sw99-chat2:#080d15;--sw99-panel:#0d1723;--sw99-panel2:#101b28;--sw99-input:#0b1521;--sw99-text:#e7eef7;--sw99-muted:#8298ad}
html,body{background:var(--sw99-body)!important;color:var(--sw99-text)!important}
[id^="m-messages_"]{background:linear-gradient(180deg,var(--sw99-chat1),var(--sw99-chat2))!important;color:var(--sw99-text)!important;border-color:rgba(var(--sw99-rgb),.32)!important}
[id^="m-users_"],.m-usersList,[id^="m-rooms_"],.m-room-list,[id^="m-room-list-"]{background:linear-gradient(180deg,var(--sw99-panel),var(--sw99-panel2))!important;color:var(--sw99-text)!important;border-color:rgba(var(--sw99-rgb),.24)!important}
[id^="m-options_"],.m-usersList-header,.m-search-box{background:var(--sw99-panel)!important;color:var(--sw99-text)!important}
[id^="m-textMessage-"],.m-search-primary,[id^="m-users_"] input,.m-usersList input,[id^="m-rooms_"] input{background:var(--sw99-input)!important;color:var(--sw99-text)!important;border-color:rgba(var(--sw99-rgb),.30)!important}
[id^="m-textMessage-"]::placeholder,.m-search-primary::placeholder{color:var(--sw99-muted)!important}
#configPanel{background:linear-gradient(180deg,var(--sw99-panel2),var(--sw99-panel))!important;color:var(--sw99-text)!important;border-color:var(--sw99-accent)!important;box-shadow:0 16px 55px #0009,0 0 22px rgba(var(--sw99-rgb),.12)!important}
#configPanel h2{color:var(--sw99-text)!important;border-bottom-color:rgba(var(--sw99-rgb),.28)!important}#configPanel h2:before,#configPanel h2:after{content:none!important;display:none!important}
.swir99-mod-title{display:flex;align-items:center;gap:8px;min-width:0}.swir99-logo{color:var(--sw99-accent);text-shadow:0 0 6px rgba(var(--sw99-rgb),.25);font-weight:900}.swir99-by{color:var(--sw99-muted);font-size:11px}.swir99-ver{font-size:9px;color:var(--sw99-muted);border:1px solid rgba(var(--sw99-rgb),.25);padding:2px 5px;border-radius:999px}.swir99-badge{font-size:8px;color:var(--sw99-accent);border:1px solid rgba(var(--sw99-rgb),.30);padding:2px 6px;border-radius:999px}
#swirTheme99{margin:10px 0 4px;padding:10px;border:1px solid rgba(var(--sw99-rgb),.20);border-radius:10px;background:rgba(0,0,0,.08)}#swirTheme99 h3{margin:0 0 8px;color:var(--sw99-accent);font-size:14px}.swir99-theme-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.swir99-theme-btn{padding:8px 5px;border-radius:8px;border:1px solid rgba(var(--sw99-rgb),.22);background:rgba(255,255,255,.045);color:var(--sw99-text);font-size:10px;cursor:pointer}.swir99-theme-btn:hover,.swir99-theme-btn.active{border-color:var(--sw99-accent);box-shadow:0 0 0 2px rgba(var(--sw99-rgb),.08),0 0 12px rgba(var(--sw99-rgb),.08)}
.m-msg-item-user-login[data-swir99nick="1"]{animation:none!important;transition:none!important}.swir-mobile-99{color:#cbd9e3!important;background:transparent!important}
#friends-panel.swir97{width:365px!important;height:min(640px,calc(100vh - 105px))!important;max-width:92vw!important;max-height:none!important;overflow-y:auto!important;overflow-x:hidden!important;padding:10px 10px 88px!important;scrollbar-width:thin;scrollbar-color:rgba(var(--sw99-rgb),.55) rgba(255,255,255,.035);box-sizing:border-box!important;background:linear-gradient(180deg,var(--sw99-panel2),var(--sw99-panel))!important;color:var(--sw99-text)!important;border-color:var(--sw99-accent)!important}
#friends-panel.swir97::-webkit-scrollbar{width:8px}#friends-panel.swir97::-webkit-scrollbar-track{background:rgba(255,255,255,.035);border-radius:10px}#friends-panel.swir97::-webkit-scrollbar-thumb{background:rgba(var(--sw99-rgb),.55);border-radius:10px}
#friends-panel.swir97 .r97r{padding:6px 2px!important}#friends-panel.swir97 .r97n{font-size:11px!important}#friends-panel.swir97 .r97s{font-size:9px!important;line-height:1.3!important}#friends-panel.swir97 .r97i{font-size:9px!important;padding:6px!important}#friends-panel.swir97 .r97f{font-size:8px!important;opacity:.72}#friends-panel.swir97 .r97add{display:none!important}
#swirFriendComposer99{position:fixed;z-index:10000050;display:flex;gap:6px;padding:7px;background:var(--sw99-panel);border:1px solid rgba(var(--sw99-rgb),.42);border-radius:10px;box-shadow:0 8px 28px #0008;box-sizing:border-box}
#swirFriendComposer99 input{flex:1;min-width:0;padding:8px 9px;background:var(--sw99-input);color:var(--sw99-text);border:1px solid rgba(var(--sw99-rgb),.32);border-radius:8px;outline:none;font-size:11px}#swirFriendComposer99 input:focus{border-color:var(--sw99-accent);box-shadow:0 0 0 2px rgba(var(--sw99-rgb),.09)}#swirFriendComposer99 button{padding:8px 9px;background:linear-gradient(135deg,var(--sw99-accent),var(--sw99-accent2));color:#fff;border:0;border-radius:8px;font-weight:800;cursor:pointer;font-size:10px}
html[data-swir-theme99="ice"],html[data-swir-theme99="ice"] body{background:#bfe4fb!important;color:#17324a!important}
html[data-swir-theme99="ice"] [id^="m-messages_"]{background:#fff!important;color:#17324a!important;border-color:#68bff0!important;box-shadow:0 10px 28px rgba(38,116,163,.16)!important}
html[data-swir-theme99="ice"] [id^="m-messages_"] .m-msg-item,html[data-swir-theme99="ice"] [id^="m-messages_"] .m-msg-item *:not(.m-msg-item-user-login):not(img):not(svg):not(path){color:#17324a!important;text-shadow:none!important}
html[data-swir-theme99="ice"] [id^="m-messages_"] .swir-black-chat-text{color:#17324a!important}
html[data-swir-theme99="ice"] [id^="m-messages_"] .swir-topic-card,html[data-swir-theme99="ice"] [id^="m-messages_"] .swir-system-card{background:#eef8ff!important;color:#17324a!important;border-color:#9bd4f5!important}
html[data-swir-theme99="ice"] [id^="m-users_"],html[data-swir-theme99="ice"] .m-usersList,html[data-swir-theme99="ice"] [id^="m-rooms_"],html[data-swir-theme99="ice"] .m-room-list{background:linear-gradient(180deg,#e8f6ff,#d6edfb)!important;color:#17324a!important}
html[data-swir-theme99="ice"] [id^="m-users_"] .m-list-user-item,html[data-swir-theme99="ice"] .m-usersList .m-list-user-item,html[data-swir-theme99="ice"] .m-room-list .m-room{background:rgba(255,255,255,.58)!important;color:#17324a!important;border-color:#b8ddf2!important}
html[data-swir-theme99="ice"] [id^="m-textMessage-"],html[data-swir-theme99="ice"] .m-search-primary{background:#fff!important;color:#17324a!important}
html[data-swir-theme99="ice"] #configPanel,html[data-swir-theme99="ice"] #friends-panel.swir97,html[data-swir-theme99="ice"] #swirFriendComposer99{background:linear-gradient(180deg,#f4fbff,#dcefff)!important;color:#17324a!important}
@media(max-width:760px){.swir99-theme-grid{grid-template-columns:repeat(2,minmax(0,1fr))}#friends-panel.swir97{width:min(355px,94vw)!important}}
`;document.head.appendChild(s)}
function cleanModHeader(force=0){try{let p=document.getElementById('configPanel'),h=p?.querySelector('h2');if(!h)return;let count=(h.textContent.match(/SWIR\s*\/\//gi)||[]).length,good=h.querySelector(':scope > .swir99-mod-title')&&h.querySelector('#closeConfigBtn')&&count===1;if(good&&!force)return;h.innerHTML='<span class="swir99-mod-title"><span class="swir99-logo">SWIR //</span><span>Czateria MOD</span><span class="swir99-by">by Swir</span><span class="swir99-ver">v9.9</span><span class="swir99-badge">GAMING UI</span></span><button id="closeConfigBtn" style="background:none;border:1px solid rgba(var(--sw99-rgb),.18);color:var(--sw99-text);font-size:18px;cursor:pointer;height:30px;width:30px;padding:0;line-height:26px;border-radius:8px">×</button>';h.querySelector('#closeConfigBtn').onclick=()=>p.style.display='none';if(!h.__swir99Observer){h.__swir99Observer=1;new MutationObserver(()=>setTimeout(()=>cleanModHeader(),0)).observe(h,{childList:true,subtree:true,characterData:true})}}catch(e){console.warn('SWIR99 header',e)}}
function installThemePanel(){try{let p=document.getElementById('configPanel');if(!p)return;document.getElementById('swirTheme98')?.remove();let d=p.querySelector('#swirTheme99');if(!d){let wrap=p.querySelector('h2')?.nextElementSibling||p.firstElementChild;if(!wrap)return;d=document.createElement('div');d.id='swirTheme99';d.innerHTML='<h3>🎨 Motyw całego czatu</h3><div class="swir99-theme-grid">'+Object.entries(themes).map(([id,t])=>`<button type="button" class="swir99-theme-btn" data-swir-theme99-btn="${id}">${t.name}</button>`).join('')+'</div><div style="margin-top:7px;font-size:9px;color:var(--sw99-muted)">❄️ Ice Light = białe okno wiadomości + błękitne tło. Wybór zapisuje się automatycznie.</div>';wrap.insertBefore(d,wrap.firstChild);d.querySelectorAll('[data-swir-theme99-btn]').forEach(b=>b.onclick=()=>applyTheme(b.dataset.swirTheme99Btn))}applyTheme(themeName(),0)}catch(e){console.warn('SWIR99 themes',e)}}
function friends(){try{let a=JSON.parse(localStorage.getItem(FRIEND_KEY)||'[]');return Array.isArray(a)?a.filter(Boolean):[]}catch(e){return[]}}
function saveFriends(a){localStorage.setItem(FRIEND_KEY,JSON.stringify(a))}
function addLocalFriend(n){n=String(n||'').trim();if(!n)return false;let a=friends();if(!a.some(x=>key(x)===key(n))){a.push(n);saveFriends(a)}try{window.SWIR_RADAR_DEBUG97?.scan?.()}catch(e){}try{let id=window.SWIR_RADAR_DEBUG97?.identity?.(n)?.id;if(id)window.SWIR_RADAR_DEBUG97?.syncOne?.(n)}catch(e){}return true}
function removeLocalFriend(n){saveFriends(friends().filter(x=>key(x)!==key(n)));try{window.SWIR_RADAR_DEBUG97?.scan?.()}catch(e){}return true}
function toast(m){let d=document.getElementById('swir99toast');if(!d){d=document.createElement('div');d.id='swir99toast';d.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:10000100;background:var(--sw99-panel,#0d1723);color:var(--sw99-text,#fff);border:1px solid var(--sw99-accent,#00e5ff);border-radius:9px;padding:8px 12px;font:12px Arial;box-shadow:0 8px 28px #0008';document.body.appendChild(d)}d.textContent=m;clearTimeout(d._t);d._t=setTimeout(()=>d.remove(),2600)}
let composerInput='';
function ensureFriendComposer(){try{document.getElementById('swirFriendComposer98')?.remove();let p=document.getElementById('friends-panel'),c=document.getElementById('swirFriendComposer99');if(!p?.classList.contains('swir97')){if(c){composerInput=c.querySelector('input')?.value||composerInput;c.remove()}return}if(!c){c=document.createElement('div');c.id='swirFriendComposer99';c.innerHTML='<input type="text" autocomplete="off" placeholder="Dodaj znajomego"><button type="button">➕ Dodaj</button>';document.body.appendChild(c);let i=c.querySelector('input');i.value=composerInput;i.addEventListener('input',()=>composerInput=i.value);let add=()=>{let n=i.value.trim();if(!n)return;if(addLocalFriend(n)){toast('✅ Dodano '+n+' do znajomych');composerInput='';i.value='';setTimeout(()=>window.SWIR_RADAR_DEBUG97?.scan?.(),80)}};c.querySelector('button').onclick=add;i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();add()}})}let r=p.getBoundingClientRect();c.style.width=Math.max(270,r.width-20)+'px';c.style.left=(r.left+10)+'px';c.style.top=Math.max(8,r.bottom-62)+'px'}catch(e){console.warn('SWIR99 composer',e)}}
function contextNick(cm){let h=cm?.querySelector('.context-menu-item--header');if(!h)return'';let n=String(h.textContent||'').split(/\n/).map(x=>x.trim()).filter(Boolean)[0]||'';return n.replace(/\s+/g,' ').trim()}
function patchContextMenu(cm){try{if(!cm)return;let n=contextNick(cm);if(!n)return;let old=cm.querySelector('.context-menu-item--friend');let item=old?old.cloneNode(true):document.createElement('div');if(old)old.replaceWith(item);else{item.className='context-menu-item context-menu-item--friend';item.style.padding='5px 10px';cm.appendChild(item)}let has=friends().some(x=>key(x)===key(n));item.textContent=has?'👋 Usuń ze znajomych SWIR':'👋 Dodaj do znajomych SWIR';item.onclick=e=>{e.preventDefault();e.stopPropagation();has?removeLocalFriend(n):addLocalFriend(n);cm.remove();toast((has?'➖ Usunięto ':'✅ Dodano ')+n);setTimeout(()=>window.SWIR_RADAR_DEBUG97?.scan?.(),100)}}catch(e){console.warn('SWIR99 context',e)}}
function scanContexts(root=document){root.querySelectorAll?.('.context-menu').forEach(patchContextMenu)}
installCss();applyTheme(themeName(),0);sweepNicks();cleanModHeader(1);installThemePanel();ensureFriendComposer();scanContexts();
const mo=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1){if(n.matches?.('.m-msg-item-user-login'))decorateNick(n);sweepNicks(n);if(n.matches?.('.context-menu'))patchContextMenu(n);scanContexts(n)}clearTimeout(window.__swir99uit);window.__swir99uit=setTimeout(()=>{cleanModHeader();installThemePanel();ensureFriendComposer()},70)});mo.observe(document.body,{childList:true,subtree:true});
setInterval(()=>{ensureFriendComposer();scanContexts();cleanModHeader();installThemePanel()},900);addEventListener('resize',ensureFriendComposer);
window.SWIR_UI99={version:'9.9',applyTheme,themes,addFriend:addLocalFriend,removeFriend:removeLocalFriend,refresh:()=>{applyTheme(themeName(),0);sweepNicks();cleanModHeader(1);installThemePanel();ensureFriendComposer();scanContexts()}};
console.log('✅ SWIR 9.9 FINAL POLISH: clean MOD + Ice Light + slim scrollable friends');
}catch(e){console.error('SWIR UI99 fatal',e)}})();
