/* SWIR 9.8 UI/UX — stable friend composer + context friend + full themes + clean MOD */
(()=>{try{
if(window.__SWIR_UI98)return;window.__SWIR_UI98=1;
window.SWIR_UI_VERSION='9.8 UI/UX';
const FRIEND_KEY='czateria_znajomi', THEME_KEY='swir_theme_98';
const pal=['#59e8ff','#75f0bd','#ffd36a','#ff8fd3','#a9a2ff','#ff9c68','#8ee66b','#6fb7ff','#f78686','#d0a0ff','#67f0e1','#f6b0ff'];
const key=n=>String(n||'').trim().toLocaleLowerCase('pl-PL');
function hash(s){let h=2166136261;for(const c of key(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h)}
function nickColor(n){return pal[hash(n)%pal.length]}
function conns(){let z=new Set();try{let m=CHNS.connManager,c=m.getCurrentConnection?.();c&&z.add(c);c=m.getFirstConnection?.();c&&z.add(c);Object.values(CHNS.channelManager?.channels||{}).forEach(ch=>{try{let x=m.getConnectionRelatedWithId?.(ch?.getChannelId?.());x&&z.add(x)}catch(e){}})}catch(e){}return[...z]}
function isMobile(n){for(const c of conns())try{let u=c.getUserWithName?.(n);if(u)return !!(u.isMobile?.()||u.isMobileUser)}catch(e){}return false}
function nickText(el){return String(el?.childNodes?.[0]?.textContent||el?.textContent||'').replace(/\s*:\s*$/,'').trim()}
function decorateNick(el){try{if(!el||el.dataset.swir98nick==='1')return;let n=nickText(el);if(!n)return;el.dataset.swir98nick='1';el.style.setProperty('color',nickColor(n),'important');el.style.setProperty('font-weight','800','important');el.style.setProperty('text-shadow','0 0 4px currentColor','important');el.style.setProperty('animation','none','important');el.style.setProperty('transition','none','important');if(isMobile(n)&&!el.querySelector('.swir-mobile-98')){let b=document.createElement('span');b.className='swir-mobile-98';b.textContent=' 📱';b.title='Użytkownik mobilny';b.style.cssText='font-size:9px;opacity:.56;text-shadow:none!important;filter:none!important';el.appendChild(b)}}catch(e){}}
function sweepNicks(root=document){root.querySelectorAll?.('[id^="m-messages_"] .m-msg-item-user-login').forEach(decorateNick)}
const themes={
 gaming:{name:'🎮 Gaming Neon',accent:'#00e5ff',accent2:'#7657ff',rgb:'0,229,255',body:'#05080d',chat1:'#0a1019',chat2:'#080d15',panel:'#0d1723',panel2:'#101b28',input:'#0b1521',text:'#e7eef7',muted:'#8298ad'},
 steel:{name:'🩶 Steel Gray',accent:'#a8d8ff',accent2:'#7896b2',rgb:'168,216,255',body:'#20242a',chat1:'#3a414a',chat2:'#2f353d',panel:'#333a43',panel2:'#3c444e',input:'#2f363e',text:'#f3f6f8',muted:'#c0c8cf'},
 matrix:{name:'🟢 Matrix',accent:'#43ff8b',accent2:'#18b85d',rgb:'67,255,139',body:'#030906',chat1:'#07130d',chat2:'#040d08',panel:'#08160f',panel2:'#0b1c13',input:'#07150e',text:'#dfffea',muted:'#88b99a'},
 ocean:{name:'🌊 Ocean',accent:'#45d9ff',accent2:'#2580ff',rgb:'69,217,255',body:'#041018',chat1:'#081d29',chat2:'#061720',panel:'#0a2230',panel2:'#0d2b3c',input:'#092331',text:'#e6f8ff',muted:'#8bb8c8'},
 violet:{name:'💜 Violet',accent:'#d28cff',accent2:'#755cff',rgb:'210,140,255',body:'#0b0711',chat1:'#191126',chat2:'#120c1c',panel:'#1a1226',panel2:'#241732',input:'#191125',text:'#f5ebff',muted:'#b9a2c9'}
};
function themeName(){let n=localStorage.getItem(THEME_KEY)||'gaming';return themes[n]?n:'gaming'}
function applyTheme(n,save=1){if(!themes[n])n='gaming';let t=themes[n],r=document.documentElement;r.dataset.swirTheme98=n;r.style.setProperty('--sw98-accent',t.accent);r.style.setProperty('--sw98-accent2',t.accent2);r.style.setProperty('--sw98-rgb',t.rgb);r.style.setProperty('--sw98-body',t.body);r.style.setProperty('--sw98-chat1',t.chat1);r.style.setProperty('--sw98-chat2',t.chat2);r.style.setProperty('--sw98-panel',t.panel);r.style.setProperty('--sw98-panel2',t.panel2);r.style.setProperty('--sw98-input',t.input);r.style.setProperty('--sw98-text',t.text);r.style.setProperty('--sw98-muted',t.muted);r.style.setProperty('--swir-a',t.accent);r.style.setProperty('--swir-b',t.accent2);r.style.setProperty('--swir-rgb',t.rgb);if(save)localStorage.setItem(THEME_KEY,n);document.querySelectorAll('[data-swir-theme98-btn]').forEach(b=>b.classList.toggle('active',b.dataset.swirTheme98Btn===n));}
function installCss(){let old=document.getElementById('swir-ui98css');if(old)return;let s=document.createElement('style');s.id='swir-ui98css';s.textContent=`
:root{--sw98-accent:#00e5ff;--sw98-accent2:#7657ff;--sw98-rgb:0,229,255;--sw98-body:#05080d;--sw98-chat1:#0a1019;--sw98-chat2:#080d15;--sw98-panel:#0d1723;--sw98-panel2:#101b28;--sw98-input:#0b1521;--sw98-text:#e7eef7;--sw98-muted:#8298ad}
html,body{background:var(--sw98-body)!important;color:var(--sw98-text)!important}
[id^="m-messages_"]{background:linear-gradient(180deg,var(--sw98-chat1),var(--sw98-chat2))!important;color:var(--sw98-text)!important;border-color:rgba(var(--sw98-rgb),.32)!important}
[id^="m-users_"],.m-usersList,[id^="m-rooms_"],.m-room-list,[id^="m-room-list-"]{background:linear-gradient(180deg,var(--sw98-panel),var(--sw98-panel2))!important;color:var(--sw98-text)!important;border-color:rgba(var(--sw98-rgb),.24)!important}
[id^="m-options_"],.m-usersList-header,.m-search-box{background:var(--sw98-panel)!important;color:var(--sw98-text)!important}
[id^="m-textMessage-"],.m-search-primary,[id^="m-users_"] input,.m-usersList input,[id^="m-rooms_"] input{background:var(--sw98-input)!important;color:var(--sw98-text)!important;border-color:rgba(var(--sw98-rgb),.30)!important}
[id^="m-textMessage-"]::placeholder,.m-search-primary::placeholder{color:var(--sw98-muted)!important}
#configPanel{background:linear-gradient(180deg,var(--sw98-panel2),var(--sw98-panel))!important;color:var(--sw98-text)!important;border-color:var(--sw98-accent)!important;box-shadow:0 16px 55px #0009,0 0 22px rgba(var(--sw98-rgb),.12)!important}
#configPanel h2{color:var(--sw98-text)!important;border-bottom-color:rgba(var(--sw98-rgb),.28)!important}#configPanel h2:before,#configPanel h2:after{content:none!important;display:none!important}
.swir98-mod-title{display:flex;align-items:center;gap:8px;min-width:0}.swir98-logo{color:var(--sw98-accent);text-shadow:0 0 6px rgba(var(--sw98-rgb),.28);font-weight:900}.swir98-by{color:#9eafbf;font-size:11px}.swir98-ver{font-size:9px;color:var(--sw98-muted);border:1px solid rgba(var(--sw98-rgb),.25);padding:2px 5px;border-radius:999px}
#swirTheme98{margin:10px 0 4px;padding:10px;border:1px solid rgba(var(--sw98-rgb),.20);border-radius:10px;background:rgba(0,0,0,.12)}#swirTheme98 h3{margin:0 0 8px;color:var(--sw98-accent);font-size:14px}.swir98-theme-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px}.swir98-theme-btn{padding:8px 5px;border-radius:8px;border:1px solid rgba(var(--sw98-rgb),.22);background:rgba(255,255,255,.035);color:var(--sw98-text);font-size:10px;cursor:pointer}.swir98-theme-btn:hover,.swir98-theme-btn.active{border-color:var(--sw98-accent);box-shadow:0 0 0 2px rgba(var(--sw98-rgb),.08),0 0 12px rgba(var(--sw98-rgb),.08)}
.m-msg-item-user-login[data-swir98nick="1"]{animation:none!important;transition:none!important}.swir-mobile-98{color:#cbd9e3!important;background:transparent!important}
#friends-panel.swir97{padding-bottom:62px!important}#friends-panel.swir97 .r97add{display:none!important}
#swirFriendComposer98{position:fixed;z-index:10000050;display:flex;gap:6px;padding:7px;background:var(--sw98-panel);border:1px solid rgba(var(--sw98-rgb),.36);border-radius:10px;box-shadow:0 8px 28px #0008;box-sizing:border-box}
#swirFriendComposer98 input{flex:1;min-width:0;padding:8px 9px;background:var(--sw98-input);color:var(--sw98-text);border:1px solid rgba(var(--sw98-rgb),.30);border-radius:8px;outline:none}#swirFriendComposer98 input:focus{border-color:var(--sw98-accent);box-shadow:0 0 0 2px rgba(var(--sw98-rgb),.08)}#swirFriendComposer98 button{padding:8px 10px;background:linear-gradient(135deg,var(--sw98-accent),var(--sw98-accent2));color:#fff;border:0;border-radius:8px;font-weight:800;cursor:pointer}
@media(max-width:760px){.swir98-theme-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
`;document.head.appendChild(s)}
function cleanModHeader(){try{let p=document.getElementById('configPanel'),h=p?.querySelector('h2');if(!h)return;h.innerHTML='<span class="swir98-mod-title"><span class="swir98-logo">SWIR //</span><span>Czateria MOD</span><span class="swir98-by">by Swir</span><span class="swir98-ver">v9.8</span></span><button id="closeConfigBtn" style="background:none;border:1px solid rgba(var(--sw98-rgb),.18);color:var(--sw98-text);font-size:18px;cursor:pointer;height:30px;width:30px;padding:0;line-height:26px;border-radius:8px">×</button>';h.querySelector('#closeConfigBtn').onclick=()=>p.style.display='none'}catch(e){console.warn('SWIR98 header',e)}}
function installThemePanel(){try{let p=document.getElementById('configPanel');if(!p||p.querySelector('#swirTheme98'))return;let wrap=p.querySelector('h2')?.nextElementSibling||p.firstElementChild;if(!wrap)return;let d=document.createElement('div');d.id='swirTheme98';d.innerHTML='<h3>🎨 Motyw całego czatu</h3><div class="swir98-theme-grid">'+Object.entries(themes).map(([id,t])=>`<button type="button" class="swir98-theme-btn" data-swir-theme98-btn="${id}">${t.name}</button>`).join('')+'</div><div style="margin-top:7px;font-size:9px;color:var(--sw98-muted)">Steel Gray = jaśniejsze, szarawe okno wiadomości. Motyw zapamiętuje się automatycznie.</div>';wrap.insertBefore(d,wrap.firstChild);d.querySelectorAll('[data-swir-theme98-btn]').forEach(b=>b.onclick=()=>applyTheme(b.dataset.swirTheme98Btn));applyTheme(themeName(),0)}catch(e){console.warn('SWIR98 themes',e)}}
function friends(){try{let a=JSON.parse(localStorage.getItem(FRIEND_KEY)||'[]');return Array.isArray(a)?a.filter(Boolean):[]}catch(e){return[]}}
function saveFriends(a){localStorage.setItem(FRIEND_KEY,JSON.stringify(a))}
function addLocalFriend(n){n=String(n||'').trim();if(!n)return false;let a=friends();if(!a.some(x=>key(x)===key(n))){a.push(n);saveFriends(a)}try{window.SWIR_RADAR_DEBUG97?.scan?.()}catch(e){}try{let id=window.SWIR_RADAR_DEBUG97?.identity?.(n)?.id;if(id)window.SWIR_RADAR_DEBUG97?.syncOne?.(n)}catch(e){}return true}
function removeLocalFriend(n){saveFriends(friends().filter(x=>key(x)!==key(n)));try{window.SWIR_RADAR_DEBUG97?.scan?.()}catch(e){}return true}
function toast(m){let d=document.getElementById('swir98toast');if(!d){d=document.createElement('div');d.id='swir98toast';d.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:10000100;background:var(--sw98-panel,#0d1723);color:var(--sw98-text,#fff);border:1px solid var(--sw98-accent,#00e5ff);border-radius:9px;padding:8px 12px;font:12px Arial;box-shadow:0 8px 28px #0008';document.body.appendChild(d)}d.textContent=m;clearTimeout(d._t);d._t=setTimeout(()=>d.remove(),2600)}
let composerInput='';
function ensureFriendComposer(){try{let p=document.getElementById('friends-panel');let c=document.getElementById('swirFriendComposer98');if(!p?.classList.contains('swir97')){if(c){composerInput=c.querySelector('input')?.value||composerInput;c.remove()}return}if(!c){c=document.createElement('div');c.id='swirFriendComposer98';c.innerHTML='<input type="text" autocomplete="off" placeholder="Dodaj nick do znajomych SWIR"><button type="button">➕ Dodaj</button>';document.body.appendChild(c);let i=c.querySelector('input');i.value=composerInput;i.addEventListener('input',()=>composerInput=i.value);let add=()=>{let n=i.value.trim();if(!n)return;if(addLocalFriend(n)){toast('✅ Dodano '+n+' do znajomych');composerInput='';i.value='';setTimeout(()=>window.SWIR_RADAR_DEBUG97?.scan?.(),80)}};c.querySelector('button').onclick=add;i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();add()}})}let r=p.getBoundingClientRect(),w=Math.max(280,r.width-18);c.style.width=w+'px';c.style.left=(r.left+9)+'px';c.style.top=Math.max(8,r.bottom-54)+'px'}catch(e){console.warn('SWIR98 composer',e)}}
function contextNick(cm){let h=cm?.querySelector('.context-menu-item--header');if(!h)return'';let n=String(h.textContent||'').split(/\n/).map(x=>x.trim()).filter(Boolean)[0]||'';return n.replace(/\s+/g,' ').trim()}
function patchContextMenu(cm){try{if(!cm||cm.dataset.swir98ctx==='1')return;let n=contextNick(cm);if(!n)return;cm.dataset.swir98ctx='1';let old=cm.querySelector('.context-menu-item--friend');let item=old?old.cloneNode(true):document.createElement('div');if(old)old.replaceWith(item);else{item.className='context-menu-item context-menu-item--friend';item.style.padding='5px 10px';cm.appendChild(item)}let has=friends().some(x=>key(x)===key(n));item.textContent=has?'👋 Usuń ze znajomych SWIR':'👋 Dodaj do znajomych SWIR';item.onclick=e=>{e.preventDefault();e.stopPropagation();has?removeLocalFriend(n):addLocalFriend(n);cm.remove();toast((has?'➖ Usunięto ':'✅ Dodano ')+n);setTimeout(()=>{let p=document.getElementById('friends-panel');if(p?.classList.contains('swir97'))window.SWIR_RADAR_DEBUG97?.scan?.()},100)}}catch(e){console.warn('SWIR98 context',e)}}
function scanContexts(root=document){root.querySelectorAll?.('.context-menu').forEach(patchContextMenu)}
installCss();applyTheme(themeName(),0);sweepNicks();cleanModHeader();installThemePanel();ensureFriendComposer();scanContexts();
const mo=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1){if(n.matches?.('.m-msg-item-user-login'))decorateNick(n);sweepNicks(n);if(n.matches?.('.context-menu'))patchContextMenu(n);scanContexts(n)}clearTimeout(window.__swir98uit);window.__swir98uit=setTimeout(()=>{cleanModHeader();installThemePanel();ensureFriendComposer()},80)});mo.observe(document.body,{childList:true,subtree:true});
setInterval(()=>{ensureFriendComposer();scanContexts();cleanModHeader();installThemePanel()},700);addEventListener('resize',ensureFriendComposer);
window.SWIR_UI98={version:'9.8',applyTheme,themes,addFriend:addLocalFriend,removeFriend:removeLocalFriend,refresh:()=>{applyTheme(themeName(),0);sweepNicks();cleanModHeader();installThemePanel();ensureFriendComposer();scanContexts()}};
console.log('✅ SWIR 9.8 UI/UX: stabilne pole znajomych + prawy klik + 5 motywów + czysty MOD');
}catch(e){console.error('SWIR UI98 fatal',e)}})();
