plugins {
    id 'com.android.application'
}

android {
    namespace 'pl.swir.czateriaplus'
    compileSdk 35

    defaultConfig {
        applicationId "pl.swir.czateriaplus"
        minSdk 24
        targetSdk 35
        versionCode 990
        versionName "9.9.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
